name: CI pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # more stable than 22

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Run unit tests
        run: npm run test

      - name: Build Angular app
        run: npm run build

      - name: Serve build
        run: npx serve -l 3000 dist/angular-cicd-app/browser &

      - name: Wait for app
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run E2E tests
        run: CYPRESS_baseUrl=http://localhost:3000 npm run e2e

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}