name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Start angular app
        run: npm start &

      - name: Wait for app to start
        run: npx wait-on http://localhost:4200

      - name: Run end-to-end tests
        run: npm run e2e

      - name: Build angular app
        run: npm run build

      - name: deploy to render
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
